export const DirnameTranslateMap = {
  html: 'HTML',
  css: 'CSS',
  javascript: 'JavaScript',
  'structure-algorithm': '数据结构与算法',
  'design-pattern': '设计模式',
  'operation-system': '操作系统',
  interview: '面试系列',
  tools: '工具软件',
  senior: '框架与工程化',
  typescript: 'TypeScript',
  nodejs: 'Nodejs',
  backend: '后端',
  team: '代码协同',
  tricks: '工具集散',
  rust: 'Rust',
  'bug-fix': '踩坑笔记',
  agent: 'Agent',
  model: '模型',
  sql: '数据库',
  basic: '基础',
}