export const sidebarCache = {
  "./docs/basic/css": [
    "CSS知识点.md",
    "Flex布局.md",
  ],
  "./docs/basic/html": [
    "HTML常见问题.md",
  ],
  "./docs/basic/javascript": [
    "JS类型与常用类型判断.md",
    "JS类型转换.md",
    "JS线程机制与事件机制.md",
    "JS闭包.md",
    "JS面向对象之对象创建模式.md",
    "ES6知识点.md",
    "JS与DOM坐标计算有关的属性.md",
    "JS事件.md",
    "JS作用域与执行上下文.md",
    "JS函数.md",
    "JS原型与原型链.md",
    "JS异步任务与事件循环.md",
    "JS浏览器BOM对象.md",
  ],
  "./docs/engineer-basic/design-pattern": [
    "如何优雅的解耦if-else.md",
  ],
  "./docs/engineer-basic/operation-system": [
    "常用unix命令.md",
  ],
  "./docs/engineer-basic/structure-algorithm": [
    "三角形最小路径和(120).md",
    "二叉树的DFS.md",
    "快速排序.md",
    "详解二分查找.md",
    "算法刷题总结一.md",
    "算法刷题总结二.md",
  ],
  "./docs/engineer-basic/team": [
    "GitHub搜索技巧.md",
    "Volta常用命令.md",
    "git-rebase和git-merge区别.md",
    "工作中常见的Git命令.md",
  ],
  "./docs/mixture/interview": [
    "手撕系列.md",
    "数组转对象.md",
    "利用 Async 和 Await 创建一个并发任务队列.md",
  ],
  "./docs/mixture/tools": [
    "软件推荐.md",
    "低成本拥有自己的一个博客网站.md",
    "定时获取免费SSL证书.md",
  ],
  "./docs/senior/ai": [
    "Agent 开发思维导图.md",
    "Agent使用技巧整理.md",
    "大模型提示词技巧.md",
    "AI设计模式理解与能力选择.md",
    "RAG查询质量优化.md",
    "AI信息片段随记.md",
  ],
  "./docs/senior/backend": [
    "缓存.md",
  ],
  "./docs/senior/frontend": [
    "2023-2025年前端领域的技术演进Top5.md",
    "Vue与React各个生命周期.md",
    "web性能优化.md",
    "前端一些常用的npm库.md",
    "vite虚拟模块实现约定式路由.md",
  ],
  "./docs/senior/nodejs": [
    "Nest入门.md",
    "Nest其他相关.md",
    "Nest登录认证.md",
    "Node制作工具常用库.md",
    "Node的CPU过载保护机制.md",
    "Node的IO机制.md",
    "关于Koa中间件底层原理简单实现.md",
    "影响Node的性能因素.md",
  ],
  "./docs/senior/peculiar": [
    "一些有趣的JS工具类方法.md",
    "01.两数之和-类型体操版本.md",
    "CSS冷门技巧(一).md",
  ],
  "./docs/senior/rust": [
    "前端视角下的Rust简单概念理解.md",
    "如何在vscode中用rust刷leetcode.md",
    "Rust 中的拷贝和克隆.md",
    "理解Cell和RefCell.md",
    "理解Deref解引用.md",
    "理解Rc和Arc.md",
    "Rust生命周期的消除规则.md",
    "理解miri 与 栈借用.md",
    "Rust编译的 wasm 在 Vite 中使用.md",
  ],
  "./docs/senior/typescript": [
    "TypeScript知识点.md",
    "几个常用类型之间区别.md",
    "新版本类型体操的一些新特性.md",
    "类型体操中的一些特殊情况.md",
  ]
};